/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aim.discovery.streams.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FitMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FitMessage\",\"namespace\":\"gov.pnnl.aim.discovery.streams.avro\",\"fields\":[{\"name\":\"compound\",\"type\":\"string\"},{\"name\":\"opaRank\",\"type\":\"string\"},{\"name\":\"shyreRank\",\"type\":\"string\"},{\"name\":\"fit\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence compound;
  @Deprecated public java.lang.CharSequence opaRank;
  @Deprecated public java.lang.CharSequence shyreRank;
  @Deprecated public java.util.List<java.lang.Double> fit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public FitMessage() {}

  /**
   * All-args constructor.
   */
  public FitMessage(java.lang.CharSequence compound, java.lang.CharSequence opaRank, java.lang.CharSequence shyreRank, java.util.List<java.lang.Double> fit) {
    this.compound = compound;
    this.opaRank = opaRank;
    this.shyreRank = shyreRank;
    this.fit = fit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return compound;
    case 1: return opaRank;
    case 2: return shyreRank;
    case 3: return fit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: compound = (java.lang.CharSequence)value$; break;
    case 1: opaRank = (java.lang.CharSequence)value$; break;
    case 2: shyreRank = (java.lang.CharSequence)value$; break;
    case 3: fit = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'compound' field.
   */
  public java.lang.CharSequence getCompound() {
    return compound;
  }

  /**
   * Sets the value of the 'compound' field.
   * @param value the value to set.
   */
  public void setCompound(java.lang.CharSequence value) {
    this.compound = value;
  }

  /**
   * Gets the value of the 'opaRank' field.
   */
  public java.lang.CharSequence getOpaRank() {
    return opaRank;
  }

  /**
   * Sets the value of the 'opaRank' field.
   * @param value the value to set.
   */
  public void setOpaRank(java.lang.CharSequence value) {
    this.opaRank = value;
  }

  /**
   * Gets the value of the 'shyreRank' field.
   */
  public java.lang.CharSequence getShyreRank() {
    return shyreRank;
  }

  /**
   * Sets the value of the 'shyreRank' field.
   * @param value the value to set.
   */
  public void setShyreRank(java.lang.CharSequence value) {
    this.shyreRank = value;
  }

  /**
   * Gets the value of the 'fit' field.
   */
  public java.util.List<java.lang.Double> getFit() {
    return fit;
  }

  /**
   * Sets the value of the 'fit' field.
   * @param value the value to set.
   */
  public void setFit(java.util.List<java.lang.Double> value) {
    this.fit = value;
  }

  /** Creates a new FitMessage RecordBuilder */
  public static gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder newBuilder() {
    return new gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder();
  }
  
  /** Creates a new FitMessage RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder newBuilder(gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder other) {
    return new gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder(other);
  }
  
  /** Creates a new FitMessage RecordBuilder by copying an existing FitMessage instance */
  public static gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder newBuilder(gov.pnnl.aim.discovery.streams.avro.FitMessage other) {
    return new gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder(other);
  }
  
  /**
   * RecordBuilder for FitMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FitMessage>
    implements org.apache.avro.data.RecordBuilder<FitMessage> {

    private java.lang.CharSequence compound;
    private java.lang.CharSequence opaRank;
    private java.lang.CharSequence shyreRank;
    private java.util.List<java.lang.Double> fit;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aim.discovery.streams.avro.FitMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.compound)) {
        this.compound = data().deepCopy(fields()[0].schema(), other.compound);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.opaRank)) {
        this.opaRank = data().deepCopy(fields()[1].schema(), other.opaRank);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.shyreRank)) {
        this.shyreRank = data().deepCopy(fields()[2].schema(), other.shyreRank);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fit)) {
        this.fit = data().deepCopy(fields()[3].schema(), other.fit);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing FitMessage instance */
    private Builder(gov.pnnl.aim.discovery.streams.avro.FitMessage other) {
            super(gov.pnnl.aim.discovery.streams.avro.FitMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.compound)) {
        this.compound = data().deepCopy(fields()[0].schema(), other.compound);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.opaRank)) {
        this.opaRank = data().deepCopy(fields()[1].schema(), other.opaRank);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.shyreRank)) {
        this.shyreRank = data().deepCopy(fields()[2].schema(), other.shyreRank);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fit)) {
        this.fit = data().deepCopy(fields()[3].schema(), other.fit);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'compound' field */
    public java.lang.CharSequence getCompound() {
      return compound;
    }
    
    /** Sets the value of the 'compound' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder setCompound(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.compound = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'compound' field has been set */
    public boolean hasCompound() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'compound' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder clearCompound() {
      compound = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'opaRank' field */
    public java.lang.CharSequence getOpaRank() {
      return opaRank;
    }
    
    /** Sets the value of the 'opaRank' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder setOpaRank(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.opaRank = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'opaRank' field has been set */
    public boolean hasOpaRank() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'opaRank' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder clearOpaRank() {
      opaRank = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'shyreRank' field */
    public java.lang.CharSequence getShyreRank() {
      return shyreRank;
    }
    
    /** Sets the value of the 'shyreRank' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder setShyreRank(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.shyreRank = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'shyreRank' field has been set */
    public boolean hasShyreRank() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'shyreRank' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder clearShyreRank() {
      shyreRank = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'fit' field */
    public java.util.List<java.lang.Double> getFit() {
      return fit;
    }
    
    /** Sets the value of the 'fit' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder setFit(java.util.List<java.lang.Double> value) {
      validate(fields()[3], value);
      this.fit = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'fit' field has been set */
    public boolean hasFit() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'fit' field */
    public gov.pnnl.aim.discovery.streams.avro.FitMessage.Builder clearFit() {
      fit = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public FitMessage build() {
      try {
        FitMessage record = new FitMessage();
        record.compound = fieldSetFlags()[0] ? this.compound : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.opaRank = fieldSetFlags()[1] ? this.opaRank : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.shyreRank = fieldSetFlags()[2] ? this.shyreRank : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.fit = fieldSetFlags()[3] ? this.fit : (java.util.List<java.lang.Double>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
