package gov.pnnl.aim.discovery.interactions;

public enum SemanticInteractions {
  INITIALIZED, BOOKMARK, FIND_ON_SCREEN, RESET, REQUEST_DETAILS, CREATE_CLUSTER, MOVE_TO_GROUP, REMOVE_GROUP, REMOVE_FROM_GROUP, GET_FEATURE_WEIGHTS, CHANGE_FEATURE_WEIGHTS, FEATURE_LABELS, SEARCH,
  LABEL_CLUSTER, GET_CLUSTER, DOCUMENT_HIGHLIGHT, CREATE_CLUSTER_WITH_DOC, GET_ANNOTATION, ADD_DOC_TO_CLUSTER, GET_DOCUMENT, START_STREAM, END_STREAM, LOGIN, END_SESSION, START_READING,
  END_READING, GET_NEW_DOCS, SCROLL_LIST, SCROLL_DOC, READ_COUNT, MOVED_CLUSTER, HIGHLIGHTED, GET_DOC_WEIGHTS, CANVAS_CLICK, DOC_CLICK, LIST_CLICK, UNLOAD_DOC, NEXT_INCREMENT;
}
