/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aim.af.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ModelMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ModelMessage\",\"namespace\":\"gov.pnnl.aim.af.avro\",\"fields\":[{\"name\":\"LOB\",\"type\":\"string\"},{\"name\":\"yes_mean\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"yes_stdev\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"no_mean\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"no_stdev\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"influentialness\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence LOB;
  @Deprecated public java.util.List<java.lang.Double> yes_mean;
  @Deprecated public java.util.List<java.lang.Double> yes_stdev;
  @Deprecated public java.util.List<java.lang.Double> no_mean;
  @Deprecated public java.util.List<java.lang.Double> no_stdev;
  @Deprecated public java.util.List<java.lang.Double> influentialness;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ModelMessage() {}

  /**
   * All-args constructor.
   */
  public ModelMessage(java.lang.CharSequence LOB, java.util.List<java.lang.Double> yes_mean, java.util.List<java.lang.Double> yes_stdev, java.util.List<java.lang.Double> no_mean, java.util.List<java.lang.Double> no_stdev, java.util.List<java.lang.Double> influentialness) {
    this.LOB = LOB;
    this.yes_mean = yes_mean;
    this.yes_stdev = yes_stdev;
    this.no_mean = no_mean;
    this.no_stdev = no_stdev;
    this.influentialness = influentialness;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return LOB;
    case 1: return yes_mean;
    case 2: return yes_stdev;
    case 3: return no_mean;
    case 4: return no_stdev;
    case 5: return influentialness;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: LOB = (java.lang.CharSequence)value$; break;
    case 1: yes_mean = (java.util.List<java.lang.Double>)value$; break;
    case 2: yes_stdev = (java.util.List<java.lang.Double>)value$; break;
    case 3: no_mean = (java.util.List<java.lang.Double>)value$; break;
    case 4: no_stdev = (java.util.List<java.lang.Double>)value$; break;
    case 5: influentialness = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'LOB' field.
   */
  public java.lang.CharSequence getLOB() {
    return LOB;
  }

  /**
   * Sets the value of the 'LOB' field.
   * @param value the value to set.
   */
  public void setLOB(java.lang.CharSequence value) {
    this.LOB = value;
  }

  /**
   * Gets the value of the 'yes_mean' field.
   */
  public java.util.List<java.lang.Double> getYesMean() {
    return yes_mean;
  }

  /**
   * Sets the value of the 'yes_mean' field.
   * @param value the value to set.
   */
  public void setYesMean(java.util.List<java.lang.Double> value) {
    this.yes_mean = value;
  }

  /**
   * Gets the value of the 'yes_stdev' field.
   */
  public java.util.List<java.lang.Double> getYesStdev() {
    return yes_stdev;
  }

  /**
   * Sets the value of the 'yes_stdev' field.
   * @param value the value to set.
   */
  public void setYesStdev(java.util.List<java.lang.Double> value) {
    this.yes_stdev = value;
  }

  /**
   * Gets the value of the 'no_mean' field.
   */
  public java.util.List<java.lang.Double> getNoMean() {
    return no_mean;
  }

  /**
   * Sets the value of the 'no_mean' field.
   * @param value the value to set.
   */
  public void setNoMean(java.util.List<java.lang.Double> value) {
    this.no_mean = value;
  }

  /**
   * Gets the value of the 'no_stdev' field.
   */
  public java.util.List<java.lang.Double> getNoStdev() {
    return no_stdev;
  }

  /**
   * Sets the value of the 'no_stdev' field.
   * @param value the value to set.
   */
  public void setNoStdev(java.util.List<java.lang.Double> value) {
    this.no_stdev = value;
  }

  /**
   * Gets the value of the 'influentialness' field.
   */
  public java.util.List<java.lang.Double> getInfluentialness() {
    return influentialness;
  }

  /**
   * Sets the value of the 'influentialness' field.
   * @param value the value to set.
   */
  public void setInfluentialness(java.util.List<java.lang.Double> value) {
    this.influentialness = value;
  }

  /** Creates a new ModelMessage RecordBuilder */
  public static gov.pnnl.aim.af.avro.ModelMessage.Builder newBuilder() {
    return new gov.pnnl.aim.af.avro.ModelMessage.Builder();
  }
  
  /** Creates a new ModelMessage RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aim.af.avro.ModelMessage.Builder newBuilder(gov.pnnl.aim.af.avro.ModelMessage.Builder other) {
    return new gov.pnnl.aim.af.avro.ModelMessage.Builder(other);
  }
  
  /** Creates a new ModelMessage RecordBuilder by copying an existing ModelMessage instance */
  public static gov.pnnl.aim.af.avro.ModelMessage.Builder newBuilder(gov.pnnl.aim.af.avro.ModelMessage other) {
    return new gov.pnnl.aim.af.avro.ModelMessage.Builder(other);
  }
  
  /**
   * RecordBuilder for ModelMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ModelMessage>
    implements org.apache.avro.data.RecordBuilder<ModelMessage> {

    private java.lang.CharSequence LOB;
    private java.util.List<java.lang.Double> yes_mean;
    private java.util.List<java.lang.Double> yes_stdev;
    private java.util.List<java.lang.Double> no_mean;
    private java.util.List<java.lang.Double> no_stdev;
    private java.util.List<java.lang.Double> influentialness;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aim.af.avro.ModelMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aim.af.avro.ModelMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.LOB)) {
        this.LOB = data().deepCopy(fields()[0].schema(), other.LOB);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.yes_mean)) {
        this.yes_mean = data().deepCopy(fields()[1].schema(), other.yes_mean);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.yes_stdev)) {
        this.yes_stdev = data().deepCopy(fields()[2].schema(), other.yes_stdev);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.no_mean)) {
        this.no_mean = data().deepCopy(fields()[3].schema(), other.no_mean);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.no_stdev)) {
        this.no_stdev = data().deepCopy(fields()[4].schema(), other.no_stdev);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.influentialness)) {
        this.influentialness = data().deepCopy(fields()[5].schema(), other.influentialness);
        fieldSetFlags()[5] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ModelMessage instance */
    private Builder(gov.pnnl.aim.af.avro.ModelMessage other) {
            super(gov.pnnl.aim.af.avro.ModelMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.LOB)) {
        this.LOB = data().deepCopy(fields()[0].schema(), other.LOB);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.yes_mean)) {
        this.yes_mean = data().deepCopy(fields()[1].schema(), other.yes_mean);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.yes_stdev)) {
        this.yes_stdev = data().deepCopy(fields()[2].schema(), other.yes_stdev);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.no_mean)) {
        this.no_mean = data().deepCopy(fields()[3].schema(), other.no_mean);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.no_stdev)) {
        this.no_stdev = data().deepCopy(fields()[4].schema(), other.no_stdev);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.influentialness)) {
        this.influentialness = data().deepCopy(fields()[5].schema(), other.influentialness);
        fieldSetFlags()[5] = true;
      }
    }

    /** Gets the value of the 'LOB' field */
    public java.lang.CharSequence getLOB() {
      return LOB;
    }
    
    /** Sets the value of the 'LOB' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setLOB(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.LOB = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'LOB' field has been set */
    public boolean hasLOB() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'LOB' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearLOB() {
      LOB = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'yes_mean' field */
    public java.util.List<java.lang.Double> getYesMean() {
      return yes_mean;
    }
    
    /** Sets the value of the 'yes_mean' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setYesMean(java.util.List<java.lang.Double> value) {
      validate(fields()[1], value);
      this.yes_mean = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'yes_mean' field has been set */
    public boolean hasYesMean() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'yes_mean' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearYesMean() {
      yes_mean = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'yes_stdev' field */
    public java.util.List<java.lang.Double> getYesStdev() {
      return yes_stdev;
    }
    
    /** Sets the value of the 'yes_stdev' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setYesStdev(java.util.List<java.lang.Double> value) {
      validate(fields()[2], value);
      this.yes_stdev = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'yes_stdev' field has been set */
    public boolean hasYesStdev() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'yes_stdev' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearYesStdev() {
      yes_stdev = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'no_mean' field */
    public java.util.List<java.lang.Double> getNoMean() {
      return no_mean;
    }
    
    /** Sets the value of the 'no_mean' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setNoMean(java.util.List<java.lang.Double> value) {
      validate(fields()[3], value);
      this.no_mean = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'no_mean' field has been set */
    public boolean hasNoMean() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'no_mean' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearNoMean() {
      no_mean = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'no_stdev' field */
    public java.util.List<java.lang.Double> getNoStdev() {
      return no_stdev;
    }
    
    /** Sets the value of the 'no_stdev' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setNoStdev(java.util.List<java.lang.Double> value) {
      validate(fields()[4], value);
      this.no_stdev = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'no_stdev' field has been set */
    public boolean hasNoStdev() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'no_stdev' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearNoStdev() {
      no_stdev = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'influentialness' field */
    public java.util.List<java.lang.Double> getInfluentialness() {
      return influentialness;
    }
    
    /** Sets the value of the 'influentialness' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder setInfluentialness(java.util.List<java.lang.Double> value) {
      validate(fields()[5], value);
      this.influentialness = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'influentialness' field has been set */
    public boolean hasInfluentialness() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'influentialness' field */
    public gov.pnnl.aim.af.avro.ModelMessage.Builder clearInfluentialness() {
      influentialness = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public ModelMessage build() {
      try {
        ModelMessage record = new ModelMessage();
        record.LOB = fieldSetFlags()[0] ? this.LOB : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.yes_mean = fieldSetFlags()[1] ? this.yes_mean : (java.util.List<java.lang.Double>) defaultValue(fields()[1]);
        record.yes_stdev = fieldSetFlags()[2] ? this.yes_stdev : (java.util.List<java.lang.Double>) defaultValue(fields()[2]);
        record.no_mean = fieldSetFlags()[3] ? this.no_mean : (java.util.List<java.lang.Double>) defaultValue(fields()[3]);
        record.no_stdev = fieldSetFlags()[4] ? this.no_stdev : (java.util.List<java.lang.Double>) defaultValue(fields()[4]);
        record.influentialness = fieldSetFlags()[5] ? this.influentialness : (java.util.List<java.lang.Double>) defaultValue(fields()[5]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
