/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aim.af.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ProportionsMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProportionsMessage\",\"namespace\":\"gov.pnnl.aim.af.avro\",\"fields\":[{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"startdate\",\"type\":\"string\"},{\"name\":\"enddate\",\"type\":\"string\"},{\"name\":\"proportions\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence company;
  @Deprecated public java.lang.CharSequence startdate;
  @Deprecated public java.lang.CharSequence enddate;
  @Deprecated public java.util.List<java.lang.Double> proportions;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public ProportionsMessage() {}

  /**
   * All-args constructor.
   */
  public ProportionsMessage(java.lang.CharSequence company, java.lang.CharSequence startdate, java.lang.CharSequence enddate, java.util.List<java.lang.Double> proportions) {
    this.company = company;
    this.startdate = startdate;
    this.enddate = enddate;
    this.proportions = proportions;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return company;
    case 1: return startdate;
    case 2: return enddate;
    case 3: return proportions;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: company = (java.lang.CharSequence)value$; break;
    case 1: startdate = (java.lang.CharSequence)value$; break;
    case 2: enddate = (java.lang.CharSequence)value$; break;
    case 3: proportions = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'company' field.
   */
  public java.lang.CharSequence getCompany() {
    return company;
  }

  /**
   * Sets the value of the 'company' field.
   * @param value the value to set.
   */
  public void setCompany(java.lang.CharSequence value) {
    this.company = value;
  }

  /**
   * Gets the value of the 'startdate' field.
   */
  public java.lang.CharSequence getStartdate() {
    return startdate;
  }

  /**
   * Sets the value of the 'startdate' field.
   * @param value the value to set.
   */
  public void setStartdate(java.lang.CharSequence value) {
    this.startdate = value;
  }

  /**
   * Gets the value of the 'enddate' field.
   */
  public java.lang.CharSequence getEnddate() {
    return enddate;
  }

  /**
   * Sets the value of the 'enddate' field.
   * @param value the value to set.
   */
  public void setEnddate(java.lang.CharSequence value) {
    this.enddate = value;
  }

  /**
   * Gets the value of the 'proportions' field.
   */
  public java.util.List<java.lang.Double> getProportions() {
    return proportions;
  }

  /**
   * Sets the value of the 'proportions' field.
   * @param value the value to set.
   */
  public void setProportions(java.util.List<java.lang.Double> value) {
    this.proportions = value;
  }

  /** Creates a new ProportionsMessage RecordBuilder */
  public static gov.pnnl.aim.af.avro.ProportionsMessage.Builder newBuilder() {
    return new gov.pnnl.aim.af.avro.ProportionsMessage.Builder();
  }
  
  /** Creates a new ProportionsMessage RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aim.af.avro.ProportionsMessage.Builder newBuilder(gov.pnnl.aim.af.avro.ProportionsMessage.Builder other) {
    return new gov.pnnl.aim.af.avro.ProportionsMessage.Builder(other);
  }
  
  /** Creates a new ProportionsMessage RecordBuilder by copying an existing ProportionsMessage instance */
  public static gov.pnnl.aim.af.avro.ProportionsMessage.Builder newBuilder(gov.pnnl.aim.af.avro.ProportionsMessage other) {
    return new gov.pnnl.aim.af.avro.ProportionsMessage.Builder(other);
  }
  
  /**
   * RecordBuilder for ProportionsMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProportionsMessage>
    implements org.apache.avro.data.RecordBuilder<ProportionsMessage> {

    private java.lang.CharSequence company;
    private java.lang.CharSequence startdate;
    private java.lang.CharSequence enddate;
    private java.util.List<java.lang.Double> proportions;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aim.af.avro.ProportionsMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aim.af.avro.ProportionsMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.company)) {
        this.company = data().deepCopy(fields()[0].schema(), other.company);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startdate)) {
        this.startdate = data().deepCopy(fields()[1].schema(), other.startdate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enddate)) {
        this.enddate = data().deepCopy(fields()[2].schema(), other.enddate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.proportions)) {
        this.proportions = data().deepCopy(fields()[3].schema(), other.proportions);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing ProportionsMessage instance */
    private Builder(gov.pnnl.aim.af.avro.ProportionsMessage other) {
            super(gov.pnnl.aim.af.avro.ProportionsMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.company)) {
        this.company = data().deepCopy(fields()[0].schema(), other.company);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.startdate)) {
        this.startdate = data().deepCopy(fields()[1].schema(), other.startdate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enddate)) {
        this.enddate = data().deepCopy(fields()[2].schema(), other.enddate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.proportions)) {
        this.proportions = data().deepCopy(fields()[3].schema(), other.proportions);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'company' field */
    public java.lang.CharSequence getCompany() {
      return company;
    }
    
    /** Sets the value of the 'company' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder setCompany(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.company = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'company' field has been set */
    public boolean hasCompany() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'company' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder clearCompany() {
      company = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'startdate' field */
    public java.lang.CharSequence getStartdate() {
      return startdate;
    }
    
    /** Sets the value of the 'startdate' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder setStartdate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.startdate = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'startdate' field has been set */
    public boolean hasStartdate() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'startdate' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder clearStartdate() {
      startdate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'enddate' field */
    public java.lang.CharSequence getEnddate() {
      return enddate;
    }
    
    /** Sets the value of the 'enddate' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder setEnddate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.enddate = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'enddate' field has been set */
    public boolean hasEnddate() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'enddate' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder clearEnddate() {
      enddate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'proportions' field */
    public java.util.List<java.lang.Double> getProportions() {
      return proportions;
    }
    
    /** Sets the value of the 'proportions' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder setProportions(java.util.List<java.lang.Double> value) {
      validate(fields()[3], value);
      this.proportions = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'proportions' field has been set */
    public boolean hasProportions() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'proportions' field */
    public gov.pnnl.aim.af.avro.ProportionsMessage.Builder clearProportions() {
      proportions = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public ProportionsMessage build() {
      try {
        ProportionsMessage record = new ProportionsMessage();
        record.company = fieldSetFlags()[0] ? this.company : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.startdate = fieldSetFlags()[1] ? this.startdate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.enddate = fieldSetFlags()[2] ? this.enddate : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.proportions = fieldSetFlags()[3] ? this.proportions : (java.util.List<java.lang.Double>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
