/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package gov.pnnl.aim.streams.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CompoundPredictMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CompoundPredictMessage\",\"namespace\":\"gov.pnnl.aim.streams.avro\",\"fields\":[{\"name\":\"probabilities\",\"type\":{\"type\":\"array\",\"items\":\"double\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<java.lang.Double> probabilities;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CompoundPredictMessage() {}

  /**
   * All-args constructor.
   */
  public CompoundPredictMessage(java.util.List<java.lang.Double> probabilities) {
    this.probabilities = probabilities;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return probabilities;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: probabilities = (java.util.List<java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'probabilities' field.
   */
  public java.util.List<java.lang.Double> getProbabilities() {
    return probabilities;
  }

  /**
   * Sets the value of the 'probabilities' field.
   * @param value the value to set.
   */
  public void setProbabilities(java.util.List<java.lang.Double> value) {
    this.probabilities = value;
  }

  /** Creates a new CompoundPredictMessage RecordBuilder */
  public static gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder newBuilder() {
    return new gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder();
  }
  
  /** Creates a new CompoundPredictMessage RecordBuilder by copying an existing Builder */
  public static gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder newBuilder(gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder other) {
    return new gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder(other);
  }
  
  /** Creates a new CompoundPredictMessage RecordBuilder by copying an existing CompoundPredictMessage instance */
  public static gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder newBuilder(gov.pnnl.aim.streams.avro.CompoundPredictMessage other) {
    return new gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder(other);
  }
  
  /**
   * RecordBuilder for CompoundPredictMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CompoundPredictMessage>
    implements org.apache.avro.data.RecordBuilder<CompoundPredictMessage> {

    private java.util.List<java.lang.Double> probabilities;

    /** Creates a new Builder */
    private Builder() {
      super(gov.pnnl.aim.streams.avro.CompoundPredictMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.probabilities)) {
        this.probabilities = data().deepCopy(fields()[0].schema(), other.probabilities);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CompoundPredictMessage instance */
    private Builder(gov.pnnl.aim.streams.avro.CompoundPredictMessage other) {
            super(gov.pnnl.aim.streams.avro.CompoundPredictMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.probabilities)) {
        this.probabilities = data().deepCopy(fields()[0].schema(), other.probabilities);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'probabilities' field */
    public java.util.List<java.lang.Double> getProbabilities() {
      return probabilities;
    }
    
    /** Sets the value of the 'probabilities' field */
    public gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder setProbabilities(java.util.List<java.lang.Double> value) {
      validate(fields()[0], value);
      this.probabilities = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'probabilities' field has been set */
    public boolean hasProbabilities() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'probabilities' field */
    public gov.pnnl.aim.streams.avro.CompoundPredictMessage.Builder clearProbabilities() {
      probabilities = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public CompoundPredictMessage build() {
      try {
        CompoundPredictMessage record = new CompoundPredictMessage();
        record.probabilities = fieldSetFlags()[0] ? this.probabilities : (java.util.List<java.lang.Double>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
